解像度の調整ありで失敗した場合、解像度の調整なしでリトライする
shiguredo/sora-android-sdk pull request #76
Opened 2022-05-25 01:14 UTC by enm10k

2022-05-26 05:07 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +                return initEncode(settings, callback)
POC なのでまだ良いのですが、再帰的に呼び出すパターンは常に潜在的な無限ループを注意する必要があります。

(特に POC だと色々いじりまくって無限ループにハマることもある (^_^;))

最終的には潜在的なループがなくなると良いですね

2022-05-26 05:13 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +                val oldSettings = calculator!!.originalSettings
ここは originalSettings を使うべきところかちょっと疑問が残りますね。

1. initEncode()
2. encode() で frame サイズが変わった
3. encoder.encode() でエラー発生
4. originalSettings は initEncode() でもらったもののはずだが、使うべき解像度は 2. で渡ってきた frame の解像度では?

2022-05-26 05:15 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +                val oldSettings = calculator!!.originalSettings
もしかすると CropSizeCalculator で originalSettings と lastFrameWidth, lastFrameHeight をダブって持っているのが複雑さを増しているかもしれないですね。
もしかしたら lastFrame* だけで良いのかもしれない。(未確認)

2022-05-26 05:18 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +                val oldSettings = calculator!!.originalSettings
もうひとつ、嫌なパスが思い浮かんだのでメモだけ(ここまで POC で対応するかは議論の余地あり)

一度 encode で例外が起きて crop なしになったあとに、(帯域が増えたとかで)解像度が大きくなって crop ありじゃないと通らなくなったばあいに、crop ありモードに復帰する必要がある(か?)

2022-05-26 05:22 UTC, shino requested changes
一旦コメント入れたので request changes にしておきます。また必要なときはいつでもメンション歓迎です!!

2022-05-26 05:22 UTC, enm10k commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +                return initEncode(settings, callback)
そうですね
一応 ... `CropSizeCalculator(oldSettings, 1u)` の時点で isCropRequired は false になるはずですが、構造的に工夫する余地がありそうです

ありがとうございます

2022-05-26 05:36 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +                return initEncode(settings, callback)
はい、「今のコードなら」問題ないのは間違いないです。
ここと関係ない部分をいじって潜在ループを踏むのが怖いんですね。

コード全体をきっちり理解してなくてもバグりにくい、というコードにしておいたほうがいろいろ良いです。
2 年後にこのことを覚えてるかどうかもわからないですし :sweat_smile:

2022-05-27 06:57 UTC, shino commented
完全に見逃してましたが configure() は例外吐くと catch して return してるんすね

https://source.chromium.org/chromium/chromium/src/+/master:third_party/webrtc/sdk/android/src/java/org/webrtc/HardwareVideoEncoder.java;l=288

2022-06-08 04:48 UTC, torikizi approved these changes

2022-06-08 06:43 UTC, enm10k commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +            if (calculator?.isCropRequired == true) {
メモ: 
ここで `retryingWithoutCrop` が false であることをチェックすれば、リトライが無限に続くことは防げそう
encode にも同様のチェックを追加すると良さそう

2022-06-08 06:48 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +            if (calculator?.isCropRequired == true) {
if とかで逃げるのはたいてい危険です(いまはうまく行ったとしても将来的に)。

モードを導入して、「ひと目で見て無限ループにならない」コードにすることをおすすめします。

2022-06-08 06:49 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +            if (calculator?.isCropRequired == true) {
難しいけどw

2022-06-08 07:12 UTC, enm10k commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +            if (calculator?.isCropRequired == true) {
`リトライ中というフラグが立ってる時は再度リトライしない` というコードを書くので、一応モード的なものではあると思うんですよね
(if 使うのは避けられてませんが ...)

構造的な話でいうと、 catch の中で再起呼び出しをしてるのを止められるとベストだと思います

2022-06-08 07:19 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +            if (calculator?.isCropRequired == true) {
たしかにリトライ中フラグなら良さそうですね

2022-06-08 09:46 UTC, enm10k commented
> どうも originalSettings が複雑さを(必要以上に?)増しているような気がしています。

以下のような仮説を持っています

- クロップのあり/なしに関わらず CropSizeCalculator を作って利用しているため複雑さを増している
- 上記のような設計でなければ、そもそも originalSettings は不要かもしれない?

コードを書き始めた際は上記の設計で良いと考えていましたが、この前提条件を見直すとコードの量も減って簡単になるかもしれません

> もうひとつは initEncode() と encode() からの crop 解像度変わったか判断ロジックの使い方です。
> ...
> このへんを明確にすると全体の見通しが良くなる気がしています

こちらも併せても少し検討してみます

2022-06-09 10:26 UTC, enm10k commented
コードを全体的に見直しました

> クロップのあり/なしに関わらず CropSizeCalculator を作って利用しているため複雑さを増している

結論としては、 CropSizeCalculator が常に存在するコードでもシンプルにできた気がします

2022-06-10 00:20 UTC, shino commented
スッキリした!!!! すばらしい!!!

2022-06-10 00:32 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +    private fun retryWithoutCropping(width: Int, height: Int, retryFunc: () -> VideoCodecStatus): VideoCodecStatus {
いいですね、これ。これが呼ばれたらリトライなんだなということが、コード上だけでわかるのでナイスです!

2022-06-10 00:38 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +                    SoraLogger.e(TAG, "initEncode() returned FALLBACK_SOFTWARE: croppedSettings $croppedSettings")
好みレベルではあるのですが、僕の好みをコメント。
TAG=HardwareVideoEncoderWrapper で、メッセージが 「initEncode() が...」だと HardwareVideoEncoderWrapper 自体の initEncode() がエラー吐いたと読めてしまうのですよね。
なので、"encoder.initEncode() returned ..." とするほうがログだけ読む人にはわかりやすいと思います。

もちょっというと、 encoder が何を指すか(ログだけだと)ちょっと微妙なので、Slack に貼ったコードでは internalEncoder という名前を使っていました(フィールド自体も)。
wrappedEncoder とか hardwareEncoder とかの名前でもいいかもしれません。

参考まで。

2022-06-10 00:40 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +        // 動作確認をした限り、ネットワーク帯域などに起因してダウンサイズが発生した場合は、 encode の前に initEncode が呼ばれていた
「現象」についてのコメントは日付か、スナップショットがわかる情報を入れておくと2年後に助かることがあります。この場合は libwebrtc のバージョンかコミットハッシュを入れておくのがいいのかもしれませんね。

2022-06-10 00:41 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +                var result = encoder.encode(croppedFrame, encodeInfo)
val でよさそう?

2022-06-10 00:43 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +                return initEncode(settings, callback)
完全に解決 :+1:

2022-06-10 00:44 UTC, shino commented
CHANGES をお願いします

2022-06-15 01:21 UTC, enm10k commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +                    SoraLogger.e(TAG, "initEncode() returned FALLBACK_SOFTWARE: croppedSettings $croppedSettings")
[640e1ed](https://github.com/shiguredo/sora-android-sdk/pull/76/commits/640e1ed05c08ed4637902d7ecce82c7473f3f291) で対応しました

2022-06-15 01:22 UTC, enm10k commented
> CHANGES をお願いします

[249c1e3](https://github.com/shiguredo/sora-android-sdk/pull/76/commits/249c1e3107a3a67e879703339259b53b3dba53ec) で対応しました

2022-06-15 03:00 UTC, miosakuma commented on CHANGES.md
> +  - 加えて、解像度調整ありでエンコーダーの初期化に失敗した際に、解像度調整なしで初期化をリトライする処理も実装した
後からすいません。libwebrtc の アップデートに関わる対応なので FIX ではなくて UPDATE がよいかもしれません。後ほどこちらで変更します。

2022-06-15 03:04 UTC, enm10k commented on CHANGES.md
> +  - 加えて、解像度調整ありでエンコーダーの初期化に失敗した際に、解像度調整なしで初期化をリトライする処理も実装した
ありがとうございます
SDK のユーザーから見た場合、下位互換はないと思うので、そこも検討した方が良いかもしれません

2022-06-15 03:09 UTC, miosakuma commented on CHANGES.md
> +  - 加えて、解像度調整ありでエンコーダーの初期化に失敗した際に、解像度調整なしで初期化をリトライする処理も実装した
そうですね、デフォルトで解像度が調整されてしまうので CHANGE の方がいいかもしれません

2022-06-16 00:46 UTC, shino commented on CHANGES.md
> +  - 加えて、解像度調整ありでエンコーダーの初期化に失敗した際に、解像度調整なしで初期化をリトライする処理も実装した
+1 > CHANGE

2022-06-16 00:46 UTC, shino commented on CHANGES.md
> +  - 加えて、解像度調整ありでエンコーダーの初期化に失敗した際に、解像度調整なしで初期化をリトライする処理も実装した
```suggestion
  - 加えて、解像度調整ありでエンコーダーの初期化またはエンコード処理に失敗した際に、解像度調整なしで操作をリトライする処理も実装した
```

2022-06-16 00:47 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +    private val internalEncoder: VideoEncoder,
いいね!!

2022-06-16 00:47 UTC, shino commented on sora-android-sdk/src/main/kotlin/jp/shiguredo/sora/sdk/codec/HardwareVideoEncoderWrapperFactory.kt
> +        private val originalHeight: Int,
Settings を渡さなくしたのですね。このほうがクラスの責務境界が明確になって好きです。

2022-06-16 01:00 UTC, shino approved these changes
Perfect!! すごく読みやすくなりました。無限ループにならないこともひと目でわかるので素晴らしい!

2022-06-16 01:03 UTC, shino commented on CHANGES.md
> +  - 加えて、解像度調整ありでエンコーダーの初期化に失敗した際に、解像度調整なしで初期化をリトライする処理も実装した
ひとつだけ。これが救った具体例を書いておくと良いと思います。
数年後に、「なんでこんな複雑なことしてるん? いらんのちゃうか?? でも削るの怖いなぁ」ってなるので(断言

2022-06-16 01:03 UTC, shino commented on CHANGES.md
> +  - 加えて、解像度調整ありでエンコーダーの初期化に失敗した際に、解像度調整なしで初期化をリトライする処理も実装した
コード側のコメントでもいいと思います。

2022-06-16 01:38 UTC, enm10k commented on CHANGES.md
> +  - 加えて、解像度調整ありでエンコーダーの初期化に失敗した際に、解像度調整なしで初期化をリトライする処理も実装した
[a64b533](https://github.com/shiguredo/sora-android-sdk/pull/76/commits/a64b5335cac4f031efadc4f594d3394ed277bd94) で対応しました

CHANGES.md の方に書きました

2022-06-16 01:38 UTC, enm10k commented on CHANGES.md
> +  - 加えて、解像度調整ありでエンコーダーの初期化に失敗した際に、解像度調整なしで初期化をリトライする処理も実装した
[a64b533](https://github.com/shiguredo/sora-android-sdk/pull/76/commits/a64b5335cac4f031efadc4f594d3394ed277bd94) で対応しました

2022-06-16 01:46 UTC, enm10k commented
レビューありがとうございました
修正を完了したのでマージします

2022-06-16 01:46 UTC, merged